// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260925072542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Database.Entities.Spiel", b =>
                {
                    b.Property<int>("SpielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpielId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Database.Entities.StationDaten", b =>
                {
                    b.Property<int>("StationDatenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpielId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimestampEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimestampStart")
                        .HasColumnType("TEXT");

                    b.HasKey("StationDatenId");

                    b.HasIndex("SpielId");

                    b.ToTable("GameData");
                });

            modelBuilder.Entity("Database.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnzahlMitglieder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Database.Entities.Spiel", b =>
                {
                    b.HasOne("Database.Entities.Team", "Team")
                        .WithOne("Spiel")
                        .HasForeignKey("Database.Entities.Spiel", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Database.Entities.StationDaten", b =>
                {
                    b.HasOne("Database.Entities.Spiel", "Spiel")
                        .WithMany("StationDaten")
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spiel");
                });

            modelBuilder.Entity("Database.Entities.Spiel", b =>
                {
                    b.Navigation("StationDaten");
                });

            modelBuilder.Entity("Database.Entities.Team", b =>
                {
                    b.Navigation("Spiel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
